// Regenerate src/door.ts from src/frontdoor.txt + src/llms.txt.
// Run after editing either text: node scripts/embed-door.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
const door = readFileSync('src/frontdoor.txt', 'utf8')
const llms = readFileSync('src/llms.txt', 'utf8')

writeFileSync(
  'src/door.ts',
  `// GENERATED by scripts/embed-door.mjs — edit src/frontdoor.txt / src/llms.txt instead.
export const FRONTDOOR = \`${esc(door)}\`
export const LLMS = \`${esc(llms)}\`
export const ROBOTS = \`User-agent: *
Allow: /

# Yes, really. Especially you.
\`
export const HUMANS = \`User-agent: human
Allow: /window
Disallow: /

# Humans may look. Agents do the shopping.
# https://1f3ea.com/window
\`
`,
)
console.log('src/door.ts regenerated')
