// Render the public text doors from templates, canonical facts, and the live MCP catalog.
import { readFileSync, writeFileSync } from 'node:fs'
import {
  AGENT_ONLY_BY_DESIGN,
  COLLECTION_LIMITS,
  FINE_PRINT_ROUTES,
  HOSTED_SIGNIN_LIMITS,
  IDENTITY_LIMITS,
  HOSTED_PROOF_CONTRACT,
  IDENTITY_FIELD_LIMITS,
  LISTING_SUBMISSION_RULES,
  MARKET_LIMITS,
  MARKET_ONE_LINE,
  MACHINE_WINDOW_RULE,
  ORDINARY_LISTING_CONTRACT,
  ORDINARY_PAYMENT_TERMINALS,
  PAYMENT_TRANSPORT_LIMITS,
  PUBLIC_READ_LIMITS,
  REQUEST_FIELD_CONVENTION,
  SOCIAL_LIMITS,
  WORLD_ACTIVATION_FIELDS,
  WORLD_DRAFT_FIELDS,
  WORLD_PENDING_DRAFT_RULE,
} from '../src/market-facts.ts'
import { MCP_TOOLS } from '../src/mcp-tool-catalog.ts'

const esc = value => value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
const replacements = {
  AGENT_ONLY_BY_DESIGN,
  COLLECTION_LIMITS,
  FINE_PRINT_ROUTES,
  HOSTED_SIGNIN_LIMITS,
  IDENTITY_LIMITS,
  HOSTED_PROOF_CONTRACT,
  IDENTITY_FIELD_LIMITS,
  LISTING_SUBMISSION_RULES,
  MARKET_ONE_LINE,
  MACHINE_WINDOW_RULE,
  ORDINARY_LISTING_CONTRACT,
  ORDINARY_PAYMENT_TERMINALS,
  PAYMENT_TRANSPORT_LIMITS,
  PUBLIC_READ_LIMITS,
  REQUEST_FIELD_CONVENTION,
  SOCIAL_LIMITS,
  WORLD_ACTIVATION_FIELDS,
  WORLD_DRAFT_FIELDS,
  WORLD_PENDING_DRAFT_RULE,
  TOOL_COUNT: String(MCP_TOOLS.length),
  TOOL_NAMES: MCP_TOOLS.map(tool => tool.name).join(', '),
  SHELF_PAGE: String(MARKET_LIMITS.collection.shelfPage),
  STORE_PAGE: String(MARKET_LIMITS.collection.storePage),
  COMMENTS_PAGE: String(MARKET_LIMITS.collection.listingCommentsPage),
  MERCHANTS_PAGE: String(MARKET_LIMITS.collection.merchantsPage),
  EVENTS_PAGE: String(MARKET_LIMITS.collection.eventsPage),
  TREASURY_PAGE: String(MARKET_LIMITS.collection.treasuryPage),
  WINDOW_EVENTS: String(MARKET_LIMITS.collection.windowEvents),
  WINDOW_LISTINGS: String(MARKET_LIMITS.collection.windowListings),
  WINDOW_MERCHANTS: String(MARKET_LIMITS.collection.windowMerchants),
  PURCHASE_ARTIFACTS_PAGE: String(MARKET_LIMITS.collection.purchaseArtifactsPage),
  COMMENT_FLAG_DAILY: String(MARKET_LIMITS.social.combinedCommentsAndFlagsPerUtcDay),
  VOTES_DAILY: String(MARKET_LIMITS.social.votesPerUtcDay),
  X_PAYMENT_MAX_BYTES: String(MARKET_LIMITS.paymentTransport.xPaymentHeaderMaxBytes),
  FACILITATOR_MAX_BYTES: String(MARKET_LIMITS.paymentTransport.facilitatorResponseMaxBytes),
  FACILITATOR_SECONDS: String(MARKET_LIMITS.paymentTransport.facilitatorTimeoutMs / 1000),
}

function render(name) {
  let result = readFileSync(`src/${name}.template.txt`, 'utf8')
  for (const [key, value] of Object.entries(replacements)) result = result.replaceAll(`{{${key}}}`, value)
  const unresolved = result.match(/\{\{[A-Z0-9_]+\}\}/gu)
  if (unresolved) throw new Error(`${name} has unresolved facts: ${unresolved.join(', ')}`)
  return result
}

const door = render('frontdoor')
const llms = render('llms')
const robots = readFileSync('src/robots.txt', 'utf8')
const humans = readFileSync('src/humans.txt', 'utf8')
const generated = `// GENERATED by scripts/embed-door.mjs — edit the *.template.txt, robots.txt, humans.txt, or canonical fact/catalog modules instead.\nexport const FRONTDOOR = \`${esc(door)}\`\nexport const LLMS = \`${esc(llms)}\`\nexport const ROBOTS = \`${esc(robots)}\`\nexport const HUMANS = \`${esc(humans)}\`\n`

const outputs = new Map([
  ['src/frontdoor.txt', door],
  ['src/llms.txt', llms],
  ['src/door.ts', generated],
])
if (process.argv.includes('--check')) {
  const stale = [...outputs].filter(([path, expected]) => readFileSync(path, 'utf8') !== expected).map(([path]) => path)
  if (stale.length) throw new Error(`generated public text is stale: ${stale.join(', ')}`)
  console.log('public text sources match generated output')
} else {
  for (const [path, value] of outputs) writeFileSync(path, value)
  console.log('src/frontdoor.txt, src/llms.txt, and src/door.ts regenerated')
}
