import type { Postcondition, ReleaseMigration } from './release-migration-types.ts'
import {
  columns, constraint, constraints, index, table, trigger, triggerFunction,
} from './release-migration-postconditions.ts'

export const MIGRATIONS = Object.freeze({
  'direct-payments': {
    file: 'db/migrations/20260823_direct_payments.sql',
    postconditions: [
      table('direct_purchase_intents'),
      index('direct_purchase_intents', 'direct_purchase_intents_open_unique'),
      index('direct_purchase_intents', 'direct_purchase_intents_buyer_listing_unique'),
      index('direct_purchase_intents', 'direct_purchase_intents_listing_id_id_unique'),
      { kind: 'column', table: 'purchases', name: 'direct_purchase_intent_id' },
      { kind: 'constraint', table: 'purchases', name: 'purchases_direct_intent_channel' },
      { kind: 'constraint', table: 'purchases', name: 'purchases_direct_intent_listing_fk' },
      index('purchases', 'purchases_direct_intent_unique'),
    ],
  },
  'hosted-market-signin': {
    file: 'db/migrations/20260822_hosted_market_signin.sql',
    postconditions: [
      table('oauth_authorization_requests'),
      table('oauth_authorization_codes'),
      table('oauth_token_families'),
      table('oauth_tokens'),
      table('oauth_rate_limits'),
      index('oauth_authorization_requests', 'oauth_authorization_requests_expiry'),
      index('oauth_authorization_codes', 'oauth_authorization_codes_expiry'),
      index('oauth_token_families', 'oauth_token_families_active'),
      index('oauth_tokens', 'oauth_tokens_active_expiry'),
      index('oauth_rate_limits', 'oauth_rate_limits_expiry'),
    ],
  },
  'world-payment-finality': {
    file: 'db/migrations/20260827_world_payment_finality.sql',
    postconditions: [
      table('world_payment_attempts'),
      table('listing_fee_attempts'),
      ...columns('direct_purchase_intents', [
        'payment_tx_hash', 'payment_status', 'finalized_block_number',
        'finalized_block_hash', 'finalized_block_time', 'finalized_at',
        'payment_review_reason',
      ]),
      ...columns('world_payment_attempts', [
        'world_checkout_id', 'listing_id', 'merchant_id', 'tx_hash', 'payer_wallet',
        'payee_wallet', 'amount_units', 'start_time', 'end_time', 'city_block_time',
        'verified_via', 'status', 'finalized_block_number', 'finalized_block_hash',
        'finalized_block_time', 'finalized_at', 'review_reason', 'created_at',
        'updated_at', 'completed_at',
      ]),
      ...columns('purchases', ['world_payment_attempt_id']),
      ...columns('payment_uses', [
        'world_payment_attempt_id', 'direct_purchase_intent_id', 'listing_fee_attempt_id',
      ]),
      ...columns('listing_fee_attempts', [
        'id', 'merchant_id', 'fee_request_kind', 'fee_request_hash', 'tx_hash',
        'payer_wallet', 'payee_wallet', 'asset', 'amount_usdc', 'minimum_block_time',
        'maximum_block_time', 'payment_status', 'listing_id', 'finalized_block_number',
        'finalized_block_hash', 'finalized_block_time', 'finalized_at',
        'payment_review_reason', 'world_draft_id', 'world_offer_id',
        'world_seller_handle', 'created_at', 'updated_at',
      ]),
      ...columns('fees', ['listing_fee_attempt_id', 'verification_method']),
      index('world_checkouts', 'world_checkouts_listing_merchant_id_unique'),
      index('direct_purchase_intents', 'direct_purchase_intents_payment_tx_unique'),
      index('world_payment_attempts', 'world_payment_attempts_tx_owner_unique'),
      index('world_payment_attempts', 'world_payment_attempts_listing_owner_unique'),
      index('purchases', 'purchases_world_payment_attempt_unique'),
      index('payment_uses', 'payment_uses_world_payment_attempt_unique'),
      index('payment_uses', 'payment_uses_direct_intent_unique'),
      index('listing_fee_attempts', 'listing_fee_attempts_listing_unique'),
      index('listing_fee_attempts', 'listing_fee_attempts_listing_id_id_unique'),
      index('payment_uses', 'payment_uses_listing_fee_attempt_unique'),
      index('fees', 'fees_listing_fee_attempt_unique'),
      ...constraints('direct_purchase_intents', [
        'direct_purchase_intents_payment_tx', 'direct_purchase_intents_payment_state',
        'direct_purchase_intents_finality_complete',
      ]),
      ...constraints('world_payment_attempts', [
        'world_payment_attempts_pkey', 'world_payment_attempts_merchant_id_fkey',
        'world_payment_attempts_tx_hash_check', 'world_payment_attempts_payer_wallet_check',
        'world_payment_attempts_payee_wallet_check', 'world_payment_attempts_amount_units_check',
        'world_payment_attempts_verified_via_check', 'world_payment_attempts_status_check',
        'world_payment_attempts_finalized_block_number_check',
        'world_payment_attempts_finalized_block_hash_check',
        'world_payment_attempts_review_reason_check', 'world_payment_attempt_checkout_fk',
        'world_payment_attempt_window', 'world_payment_attempt_finality_complete',
        'world_payment_attempt_state_facts', 'world_payment_attempt_timestamps',
      ]),
      constraint('purchases', 'purchases_world_payment_attempt_fk'),
      constraint('purchases', 'purchases_world_requires_payment_attempt'),
      constraint('purchases', 'purchases_claim_requires_direct_payment_intent'),
      ...constraints('payment_uses', [
        'payment_uses_world_payment_attempt_fk', 'payment_uses_direct_intent_fk',
        'payment_uses_direct_intent_channel', 'payment_uses_one_attempt_owner',
        'payment_uses_world_attempt_channel', 'payment_uses_listing_fee_attempt_fk',
        'payment_uses_listing_fee_channel', 'payment_uses_one_durable_owner',
      ]),
      ...constraints('listing_fee_attempts', [
        'listing_fee_attempts_pkey', 'listing_fee_attempts_merchant_id_fkey',
        'listing_fee_attempts_fee_request_kind_check',
        'listing_fee_attempts_fee_request_hash_check', 'listing_fee_attempts_tx_hash_key',
        'listing_fee_attempts_tx_hash_check', 'listing_fee_attempts_payer_wallet_check',
        'listing_fee_attempts_payee_wallet_check', 'listing_fee_attempts_asset_check',
        'listing_fee_attempts_amount_usdc_check',
        'listing_fee_attempts_payment_status_check', 'listing_fee_attempts_listing_id_fkey',
        'listing_fee_attempts_world_draft_id_fkey', 'listing_fee_attempt_request_unique',
        'listing_fee_attempt_window', 'listing_fee_attempt_finality_complete',
        'listing_fee_attempt_world_context', 'listing_fee_attempt_state',
      ]),
      ...constraints('fees', [
        'fees_listing_fee_attempt_fk', 'fees_verification_method_allowed',
        'fees_verification_method_link', 'fees_new_rows_not_legacy',
      ]),
      triggerFunction('protect_world_payment_attempt_terms', undefined, [
        "tg_op = 'delete'", 'old.city_block_time', "old.status <> 'payment_pending'",
      ]),
      triggerFunction('reserve_world_payment_attempt_use', undefined, [
        'insert into payment_uses', 'world_payment_attempt_id', 'new.world_checkout_id',
      ]),
      triggerFunction('protect_linked_payment_use', 'listing_fee_attempt_id', [
        'world_payment_attempt_id', 'direct_purchase_intent_id', "tg_op = 'delete'",
      ]),
      triggerFunction('protect_direct_payment_intent_history', undefined, [
        "old.payment_status <> 'unsubmitted'", 'old.finalized_block_number',
        "old.payment_status = 'payment_pending'",
      ]),
      triggerFunction('reserve_direct_payment_intent_use', undefined, [
        'insert into payment_uses', 'direct_purchase_intent_id', 'new.payment_tx_hash',
      ]),
      triggerFunction('validate_direct_payment_intent_completion', undefined, [
        "new.payment_status = 'payment_pending'", "new.payment_status = 'completed'",
        'from purchases purchase', 'direct_purchase_intent_id',
      ]),
      triggerFunction('validate_direct_purchase_attempt', undefined, [
        'new.direct_purchase_intent_id', "new.verified_via = 'claim'",
        'intent.payment_status = \'completed\'',
      ]),
      triggerFunction('claim_payment_use', 'listing_fee_attempt_id', [
        'direct_purchase_intent_id', 'world_payment_attempt_id',
        'insert into payment_uses',
      ]),
      triggerFunction('validate_world_payment_attempt_completion', undefined, [
        "new.status = 'payment_pending'", "new.status = 'completed'",
        'world_payment_attempt_id', 'from purchases purchase',
      ]),
      triggerFunction('validate_world_purchase_attempt', undefined, [
        'new.world_checkout_id = new.world_payment_attempt_id',
        "new.world_receipt->>'payment_from'", "new.world_receipt->>'payment_to'",
        "new.world_receipt->>'city_block_time'",
      ]),
      triggerFunction('protect_listing_fee_attempt_history', undefined, [
        'old.maximum_block_time', "old.payment_status in ('completed','needs_review')",
        "new.payment_status not in ('payment_pending','completed','needs_review')",
      ]),
      triggerFunction('reserve_listing_fee_attempt_use', undefined, [
        'insert into payment_uses', 'listing_fee_attempt_id', 'new.id',
      ]),
      triggerFunction('validate_listing_fee_attempt_completion', undefined, [
        'listing_fee_attempt_id = new.id', "new.payment_status = 'completed'",
        'from fees fee',
      ]),
      triggerFunction('validate_linked_listing_fee', 'verification_method', [
        'listing_fee_attempt_id', "new.verification_method = 'direct'",
      ]),
      trigger('world_payment_attempts', 'world_payment_attempt_terms_immutable',
        'protect_world_payment_attempt_terms', false, ['before', 'update', 'delete']),
      trigger('world_payment_attempts', 'world_payment_attempt_reserve_use',
        'reserve_world_payment_attempt_use', false, ['after insert']),
      trigger('world_payment_attempts', 'world_payment_attempt_completion_matches',
        'validate_world_payment_attempt_completion', true, ['after insert or update']),
      trigger('direct_purchase_intents', 'direct_payment_intent_history_immutable',
        'protect_direct_payment_intent_history', false, ['before', 'update', 'delete']),
      trigger('direct_purchase_intents', 'direct_payment_intent_reserve_use',
        'reserve_direct_payment_intent_use', false, ['after update']),
      trigger('direct_purchase_intents', 'direct_payment_intent_completion_matches',
        'validate_direct_payment_intent_completion', true, ['after insert or update']),
      trigger('purchases', 'purchases_direct_payment_intent_match',
        'validate_direct_purchase_attempt', true, ['after insert or delete or update']),
      trigger('purchases', 'purchases_world_payment_attempt_match',
        'validate_world_purchase_attempt', true, ['after insert or delete or update']),
      trigger('payment_uses', 'linked_payment_use_immutable', 'protect_linked_payment_use',
        false, ['before', 'update', 'delete']),
      trigger('listing_fee_attempts', 'listing_fee_attempt_history_immutable',
        'protect_listing_fee_attempt_history', false, ['before', 'update', 'delete']),
      trigger('listing_fee_attempts', 'listing_fee_attempt_reserve_use',
        'reserve_listing_fee_attempt_use', false, ['after insert']),
      trigger('listing_fee_attempts', 'listing_fee_attempt_completion_matches',
        'validate_listing_fee_attempt_completion', true, ['after insert or update']),
      trigger('fees', 'fees_listing_fee_attempt_match', 'validate_linked_listing_fee', true,
        ['after insert or delete or update']),
      trigger('purchases', 'payment_use_claim', 'claim_payment_use', false, ['before insert']),
      trigger('fees', 'payment_use_claim', 'claim_payment_use', false, ['before insert']),
    ],
  },
  'x402-payment-attempts': {
    file: 'db/migrations/20260828_x402_payment_attempts.sql',
    preflightTable: 'x402_payment_attempts',
    postconditions: [
      table('x402_payment_attempts'),
      ...columns('x402_payment_attempts', [
        'operation_key', 'operation_kind', 'proof_digest', 'requirements_digest',
        'network', 'asset', 'payer_wallet', 'payee_wallet', 'amount_units', 'resource',
        'authorization_nonce', 'authorization_valid_after', 'authorization_valid_before',
        'start_block', 'status', 'tx_hash', 'review_reason',
        'operation_started_at', 'settlement_started_at', 'settled_at',
        'finalized_block_number', 'finalized_block_hash', 'finalized_block_time',
        'finalized_at', 'created_at', 'updated_at',
      ]),
      ...columns('fees', ['x402_payment_operation_key']),
      ...columns('purchases', ['x402_payment_operation_key']),
      ...columns('payment_uses', ['x402_payment_operation_key']),
      index('x402_payment_attempts', 'x402_payment_attempts_reconcile'),
      index('fees', 'fees_x402_payment_attempt_unique'),
      index('purchases', 'purchases_x402_payment_attempt_unique'),
      index('payment_uses', 'payment_uses_x402_payment_attempt_unique'),
      ...constraints('x402_payment_attempts', [
        'x402_payment_attempts_pkey', 'x402_payment_attempts_operation_key_shape',
        'x402_payment_attempts_operation_kind_allowed',
        'x402_payment_attempts_proof_digest_key',
        'x402_payment_attempts_proof_digest_shape',
        'x402_payment_attempts_requirements_digest_shape',
        'x402_payment_attempts_network_base', 'x402_payment_attempts_asset_usdc',
        'x402_payment_attempts_payer_wallet_shape',
        'x402_payment_attempts_payee_wallet_shape',
        'x402_payment_attempts_amount_range', 'x402_payment_attempts_resource_size',
        'x402_payment_attempts_nonce_shape', 'x402_payment_attempts_status_allowed',
        'x402_payment_attempts_tx_hash_key', 'x402_payment_attempts_tx_hash_shape',
        'x402_payment_attempts_review_reason_size',
        'x402_payment_attempts_authorization_owner',
        'x402_payment_attempts_authorization_window',
        'x402_payment_attempts_operation_overlap',
        'x402_payment_attempts_finality_complete',
        'x402_payment_attempts_finality_anchor',
        'x402_payment_attempts_state_facts', 'x402_payment_attempts_time_order',
      ]),
      constraint('payment_uses', 'payment_uses_x402_payment_attempt_fk', {
        validated: false, deferrable: true, initiallyDeferred: true,
      }),
      constraint('payment_uses', 'payment_uses_one_durable_owner_v2', { validated: false }),
      constraint('fees', 'fees_x402_payment_attempt_fk', { validated: false }),
      constraint('fees', 'fees_x402_requires_payment_attempt', { validated: false }),
      constraint('purchases', 'purchases_x402_payment_attempt_fk', { validated: false }),
      constraint('purchases', 'purchases_x402_requires_payment_attempt', { validated: false }),
      triggerFunction('protect_x402_payment_attempt_history', undefined, [
        "tg_op = 'delete'", 'new.operation_key', 'new.proof_digest',
        'new.operation_started_at', 'old.tx_hash is not null',
        'old.finalized_block_number is not null', 'old.review_reason is not null',
        "old.status = 'verified'", "old.status = 'settled'", "old.status = 'settling'",
        "old.status = 'needs_review'",
        'new.updated_at < old.updated_at',
      ]),
      triggerFunction('validate_x402_result_link', undefined, [
        "attempt.status = 'verified'", 'attempt.tx_hash = lower(new.tx_hash)',
        'attempt.amount_units = new.amount_usdc * 1000000', 'attempt.payee_wallet',
        "attempt.operation_kind = 'world_listing_fee'", "attempt.operation_kind = 'purchase'",
      ]),
      triggerFunction('protect_x402_result_link', undefined, [
        "tg_op = 'delete'", 'old.x402_payment_operation_key',
        'new.x402_payment_operation_key', 'old.created_at',
      ]),
      triggerFunction('protect_linked_payment_use', undefined, [
        'old_x402_key', 'new_x402_key', 'linked payment use history is immutable',
      ]),
      triggerFunction('claim_payment_use', undefined, [
        'x402_payment_operation_key = $3', 'into reservation_found',
        'direct_purchase_intent_id', 'world_payment_attempt_id', 'listing_fee_attempt_id',
      ]),
      triggerFunction('reserve_x402_payment_attempt_use', undefined, [
        'insert into payment_uses', 'on conflict (tx_hash) do nothing',
        'new.updated_at := greatest', 'old.updated_at', 'new.settlement_started_at',
        'do not pay again',
      ]),
      triggerFunction('validate_x402_payment_attempt_use', undefined, [
        'x402_payment_operation_key = new.operation_key',
        'x402 payment has no matching market transaction reservation',
      ]),
      trigger(
        'x402_payment_attempts', 'x402_payment_attempts_keep_history',
        'protect_x402_payment_attempt_history', false, ['before', 'update', 'delete'],
      ),
      trigger('fees', 'fees_x402_payment_attempt_match',
        'validate_x402_result_link', true, ['after insert or update']),
      trigger('purchases', 'purchases_x402_payment_attempt_match',
        'validate_x402_result_link', true, ['after insert or update']),
      trigger('fees', 'fees_x402_result_link_immutable',
        'protect_x402_result_link', false, ['before', 'update', 'delete']),
      trigger('purchases', 'purchases_x402_result_link_immutable',
        'protect_x402_result_link', false, ['before', 'update', 'delete']),
      trigger('payment_uses', 'linked_payment_use_immutable', 'protect_linked_payment_use',
        false, ['before', 'update', 'delete']),
      trigger('x402_payment_attempts', 'x402_payment_attempt_reserve_use',
        'reserve_x402_payment_attempt_use', false, ['before', 'insert or update']),
      trigger('x402_payment_attempts', 'x402_payment_attempt_use_matches',
        'validate_x402_payment_attempt_use', true, ['after', 'insert or update']),
      trigger('purchases', 'payment_use_claim', 'claim_payment_use', false, ['before insert']),
      trigger('fees', 'payment_use_claim', 'claim_payment_use', false, ['before insert']),
    ],
  },
  'market-identity': {
    file: 'db/migrations/20260827_market_identity.sql',
    postconditions: [
      { kind: 'column', table: 'merchants', name: 'recovery_generation' },
      { kind: 'constraint', table: 'merchants', name: 'merchants_recovery_generation_nonnegative' },
      table('pending_merchant_registrations'),
      table('pending_merchant_registration_recovery_codes'),
      table('merchant_recovery_codes'),
      { kind: 'constraint', table: 'merchant_recovery_codes', name: 'merchant_recovery_codes_ceremony_state' },
      { kind: 'constraint', table: 'merchant_recovery_codes', name: 'merchant_recovery_codes_expiry_window' },
      table('merchant_recovery_ceremony_results'),
      { kind: 'constraint', table: 'merchant_recovery_ceremony_results', name: 'merchant_recovery_ceremony_results_outcome_allowed' },
      { kind: 'constraint', table: 'merchant_recovery_ceremony_results', name: 'merchant_recovery_ceremony_results_retention_window' },
      index('merchant_recovery_ceremony_results', 'merchant_recovery_ceremony_results_expiry'),
      table('merchant_key_rotations'),
      table('merchant_identity_rate_limits'),
      { kind: 'constraint', table: 'merchant_identity_rate_limits', name: 'merchant_identity_rate_limits_attempt_kind_allowed' },
      table('oauth_authorization_request_recovery_codes'),
      { kind: 'column', table: 'oauth_authorization_requests', name: 'intent' },
      { kind: 'column', table: 'oauth_authorization_requests', name: 'new_handle' },
      { kind: 'column', table: 'oauth_authorization_requests', name: 'new_model' },
      { kind: 'column', table: 'oauth_authorization_requests', name: 'new_secret_hash' },
      { kind: 'column', table: 'oauth_authorization_requests', name: 'merchant_key_confirmed_at' },
      { kind: 'constraint', table: 'oauth_authorization_requests', name: 'oauth_authorization_requests_intent_allowed' },
      { kind: 'constraint', table: 'oauth_authorization_requests', name: 'oauth_authorization_requests_identity_values' },
      { kind: 'constraint', table: 'oauth_authorization_requests', name: 'oauth_authorization_requests_identity_state' },
      { kind: 'constraint', table: 'oauth_authorization_requests', name: 'oauth_authorization_requests_key_confirmation_time' },
    ],
  },
  'market-coding-identity': {
    file: 'db/migrations/20260902_market_identity_json_doors.sql',
    preflightTable: 'merchant_pairing_codes',
    postconditions: [
      constraint('merchant_identity_rate_limits', 'merchant_identity_rate_limits_attempt_kind_allowed', {
        definitionIncludes: ['pair_create'],
      }),
      table('merchant_pairing_codes'),
      ...columns('merchant_pairing_codes', [
        'id', 'merchant_id', 'code_hash', 'created_at', 'expires_at', 'used_at', 'invalidated_at',
      ]),
      index('merchant_pairing_codes', 'merchant_pairing_codes_merchant'),
      index('merchant_pairing_codes', 'merchant_pairing_codes_expiry'),
      table('oauth_pairing_reservations'),
      ...columns('oauth_pairing_reservations', [
        'id', 'session_hash', 'csrf_hash', 'pairing_code_hash', 'merchant_id', 'expires_at', 'created_at',
      ]),
      index('oauth_pairing_reservations', 'oauth_pairing_reservations_expiry'),
    ],
  },
} as const satisfies Readonly<Record<ReleaseMigration, Readonly<{
  file: string
  postconditions: readonly Postcondition[]
  preflightTable?: string
}>>>)
